# Generated by Django 2.1.4 on 2018-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_method', models.CharField(choices=[('upload', 'UPLOAD FILE'), ('record', 'RECORD'), ('other', 'other')], default='upload', max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('recognition_package', models.CharField(choices=[('bing', 'Microsoft Bing Speech'), ('google', 'Google Web Speech API'), ('google_cloud', 'Google Cloud Speech'), ('houndify', 'Houndify'), ('ibm', 'IBM Speech to Text'), ('sphinx', ' CMU Sphinx'), ('wit', 'Wit.ai'), ('other', 'other')], default='upload', max_length=255)),
            ],
        ),
    ]
